In [5]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [6]:
df = pd.read_csv("qoute_dataset.csv")

In [7]:
df.head()

                                               quote           Author
0  “The world as we have created it is a process ...  Albert Einstein
1  “It is our choices, Harry, that show what we t...     J.K. Rowling
2  “There are only two ways to live your life. On...  Albert Einstein
3  “The person, be it gentleman or lady, who has ...      Jane Austen
4  “Imperfection is beauty, madness is genius and...   Marilyn Monroe

In [8]:
df.shape

(3038, 2)

In [9]:
quotes = df['quote']
quotes.head()

0    “The world as we have created it is a process ...
1    “It is our choices, Harry, that show what we t...
2    “There are only two ways to live your life. On...
3    “The person, be it gentleman or lady, who has ...
4    “Imperfection is beauty, madness is genius and...
Name: quote, dtype: object

Lower Case

In [10]:
quotes = quotes.str.lower()

In [11]:
quotes.head()

0    “the world as we have created it is a process ...
1    “it is our choices, harry, that show what we t...
2    “there are only two ways to live your life. on...
3    “the person, be it gentleman or lady, who has ...
4    “imperfection is beauty, madness is genius and...
Name: quote, dtype: object

Remove punctuation

In [12]:
import string
translator = str.maketrans('', '', string.punctuation)
quotes = quotes.apply(lambda x: x.translate(translator))

In [13]:
quotes.head()

0    “the world as we have created it is a process ...
1    “it is our choices harry that show what we tru...
2    “there are only two ways to live your life one...
3    “the person be it gentleman or lady who has no...
4    “imperfection is beauty madness is genius and ...
Name: quote, dtype: object

Tokenizetion

In [14]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [15]:
vocab_size = 10000

tokinizer = Tokenizer(num_words=vocab_size)
tokinizer.fit_on_texts(quotes)

In [16]:
word_index = tokinizer.word_index
print(len(word_index))
list(word_index.items())[:15]

8978

[('the', 1),
 ('you', 2),
 ('to', 3),
 ('and', 4),
 ('a', 5),
 ('i', 6),
 ('is', 7),
 ('of', 8),
 ('that', 9),
 ('it', 10),
 ('in', 11),
 ('be', 12),
 ('not', 13),
 ('are', 14),
 ('your', 15)]

In [17]:
sequence = tokinizer.texts_to_sequences(quotes)

In [18]:
for i in range(4):
  print(quotes[i])

“the world as we have created it is a process of our thinking it cannot be changed without changing our thinking”
“it is our choices harry that show what we truly are far more than our abilities”
“there are only two ways to live your life one is as though nothing is a miracle the other is as though everything is a miracle”
“the person be it gentleman or lady who has not pleasure in a good novel must be intolerably stupid”

In [19]:
for i in range(4):
  print(sequence[i])

[713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145, 12, 809, 104, 752, 70, 2461]
[947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294, 52, 54, 70, 3676]
[1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7, 5, 1157, 1, 101, 7, 29, 329, 126, 7, 5, 3677]
[713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601, 11, 5, 74, 1338, 119, 12, 2463, 3678]

In [20]:
print(tokinizer.word_index['“it'])

947

In [21]:
print(tokinizer.word_index['it'])

10

In [22]:
X = []
y = []

for seq in sequence:
  for i in range(1,len(seq)):
    input_seq = seq[:i]
    output_seq = seq[i]
    X.append(input_seq)
    y.append(output_seq)

In [23]:
len(X)

85271

In [24]:
len(y)

85271

Padding

In [25]:
max_len = max(len(x) for x in X)
print(max_len)

745

In [26]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
X_padded = pad_sequences(X, maxlen=max_len, padding='pre')

In [27]:
y = np.array(y)

In [28]:
X_padded.shape

(85271, 745)

In [29]:
y.shape

(85271,)

In [30]:
X_padded

array([[   0,    0,    0, ...,    0,    0,  713],
       [   0,    0,    0, ...,    0,  713,   62],
       [   0,    0,    0, ...,  713,   62,   29],
       ...,
       [   0,    0,    0, ...,    9,   19, 1125],
       [   0,    0,    0, ...,   19, 1125,    3],
       [   0,    0,    0, ..., 1125,    3,  169]], dtype=int32)

In [31]:
y

array([ 62,  29,  19, ...,   3, 169, 101])

One Hot Encodding

In [32]:
from tensorflow.keras.utils import to_categorical
y_one_hot = to_categorical(y, num_classes=vocab_size)

In [33]:
y_one_hot.shape

(85271, 10000)

In [34]:
y_one_hot

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [35]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,SimpleRNN, LSTM, Dense,GRU

Embedding

In [36]:
embedding_dim = 50
rnn_units = 128

RNN Model

In [37]:
rnn_model = Sequential()

rnn_model.add(
    Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_len)
)
rnn_model.add(SimpleRNN(units=rnn_units))
rnn_model.add(Dense(units=vocab_size, activation='softmax'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [38]:
rnn_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [39]:
rnn_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

LSTM Model

In [40]:
lstm_model = Sequential()
lstm_model.add(
    Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_len)
)
lstm_model.add(LSTM(units=rnn_units))
lstm_model.add(Dense(units=vocab_size, activation='softmax'))

In [41]:
lstm_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [42]:
lstm_model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

# GRU Model

In [43]:
gru_model = Sequential()

gru_model.add(
    Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_len)
)

gru_model.add(GRU(units=rnn_units))
gru_model.add(Dense(units=vocab_size, activation='softmax'))

gru_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [44]:
epochs =100
batch_size = 128
history_gru = gru_model.fit(
    X_padded,
    y_one_hot,
    epochs=100,
    batch_size=128,
    validation_split=0.1
)

Epoch 1/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 36s 49ms/step - accuracy: 0.0438 - loss: 6.8047 - val_accuracy: 0.0580 - val_loss: 6.5442
Epoch 2/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 28s 46ms/step - accuracy: 0.0813 - loss: 6.0875 - val_accuracy: 0.0960 - val_loss: 6.3243
Epoch 3/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 28s 47ms/step - accuracy: 0.1062 - loss: 5.7299 - val_accuracy: 0.1060 - val_loss: 6.2726
Epoch 4/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 28s 47ms/step - accuracy: 0.1214 - loss: 5.4391 - val_accuracy: 0.1120 - val_loss: 6.2891
Epoch 5/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 48ms/step - accuracy: 0.1373 - loss: 5.1792 - val_accuracy: 0.1157 - val_loss: 6.3255
Epoch 6/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 48ms/step - accuracy: 0.1512 - loss: 4.9387 - val_accuracy: 0.1173 - val_loss: 6.3599
Epoch 7/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 48ms/step - accuracy: 0.1645 - loss: 4.7131 - val_accuracy: 0.1195 - val_loss: 6.4220
Epoch 8/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 49ms/step - accuracy: 0.1797 - loss: 4.5015 - val_accuracy: 0.1174 - val_loss: 6.4966
Epoch 9/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 48ms/step - accuracy: 0.1963 - loss: 4.3039 - val_accuracy: 0.1176 - val_loss: 6.5636
Epoch 10/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 48ms/step - accuracy: 0.2169 - loss: 4.1177 - val_accuracy: 0.1168 - val_loss: 6.6299
Epoch 11/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 50ms/step - accuracy: 0.2394 - loss: 3.9460 - val_accuracy: 0.1187 - val_loss: 6.6914
Epoch 12/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 48ms/step - accuracy: 0.2627 - loss: 3.7851 - val_accuracy: 0.1167 - val_loss: 6.7561
Epoch 13/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 48ms/step - accuracy: 0.2837 - loss: 3.6376 - val_accuracy: 0.1146 - val_loss: 6.8303
Epoch 14/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 49ms/step - accuracy: 0.3050 - loss: 3.4986 - val_accuracy: 0.1150 - val_loss: 6.9006
Epoch 15/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 48ms/step - accuracy: 0.3246 - loss: 3.3719 - val_accuracy: 0.1109 - val_loss: 6.9638
Epoch 16/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 48ms/step - accuracy: 0.3428 - loss: 3.2557 - val_accuracy: 0.1126 - val_loss: 7.0177
Epoch 17/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 48ms/step - accuracy: 0.3610 - loss: 3.1470 - val_accuracy: 0.1073 - val_loss: 7.1062
Epoch 18/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 48ms/step - accuracy: 0.3763 - loss: 3.0464 - val_accuracy: 0.1071 - val_loss: 7.1592
Epoch 19/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 48ms/step - accuracy: 0.3919 - loss: 2.9531 - val_accuracy: 0.1071 - val_loss: 7.2343
Epoch 20/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 48ms/step - accuracy: 0.4074 - loss: 2.8641 - val_accuracy: 0.1038 - val_loss: 7.2895
Epoch 21/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 48ms/step - accuracy: 0.4214 - loss: 2.7797 - val_accuracy: 0.1057 - val_loss: 7.3590
Epoch 22/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 48ms/step - accuracy: 0.4339 - loss: 2.7041 - val_accuracy: 0.1011 - val_loss: 7.4247
Epoch 23/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 42s 50ms/step - accuracy: 0.4473 - loss: 2.6286 - val_accuracy: 0.1027 - val_loss: 7.4969
Epoch 24/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 48ms/step - accuracy: 0.4594 - loss: 2.5602 - val_accuracy: 0.0979 - val_loss: 7.5540
Epoch 25/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 48ms/step - accuracy: 0.4705 - loss: 2.4969 - val_accuracy: 0.0981 - val_loss: 7.6152
Epoch 26/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 48ms/step - accuracy: 0.4803 - loss: 2.4342 - val_accuracy: 0.0952 - val_loss: 7.6801
Epoch 27/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 48ms/step - accuracy: 0.4911 - loss: 2.3764 - val_accuracy: 0.0967 - val_loss: 7.7402
Epoch 28/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 48ms/step - accuracy: 0.5021 - loss: 2.3198 - val_accuracy: 0.0970 - val_loss: 7.7893
Epoch 29/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 49ms/step - accuracy: 0.5121 - loss: 2.2672 - val_accuracy: 0.0976 - val_loss: 7.8592
Epoch 30/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 48ms/step - accuracy: 0.5207 - loss: 2.2168 - val_accuracy: 0.0939 - val_loss: 7.9232
Epoch 31/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 48ms/step - accuracy: 0.5310 - loss: 2.1689 - val_accuracy: 0.0939 - val_loss: 7.9722
Epoch 32/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 49ms/step - accuracy: 0.5394 - loss: 2.1247 - val_accuracy: 0.0960 - val_loss: 8.0552
Epoch 33/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 48ms/step - accuracy: 0.5457 - loss: 2.0800 - val_accuracy: 0.0916 - val_loss: 8.1005
Epoch 34/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 48ms/step - accuracy: 0.5534 - loss: 2.0406 - val_accuracy: 0.0942 - val_loss: 8.1707
Epoch 35/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 49ms/step - accuracy: 0.5634 - loss: 2.0008 - val_accuracy: 0.0928 - val_loss: 8.2385
Epoch 36/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 49ms/step - accuracy: 0.5688 - loss: 1.9640 - val_accuracy: 0.0935 - val_loss: 8.2887
Epoch 37/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 49ms/step - accuracy: 0.5755 - loss: 1.9298 - val_accuracy: 0.0896 - val_loss: 8.3476
Epoch 38/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 49ms/step - accuracy: 0.5829 - loss: 1.8936 - val_accuracy: 0.0918 - val_loss: 8.4167
Epoch 39/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 48ms/step - accuracy: 0.5893 - loss: 1.8602 - val_accuracy: 0.0895 - val_loss: 8.4633
Epoch 40/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 48ms/step - accuracy: 0.5955 - loss: 1.8313 - val_accuracy: 0.0875 - val_loss: 8.5154
Epoch 41/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 49ms/step - accuracy: 0.5960 - loss: 1.8262 - val_accuracy: 0.0889 - val_loss: 8.5713
Epoch 42/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 49ms/step - accuracy: 0.6072 - loss: 1.7721 - val_accuracy: 0.0888 - val_loss: 8.6097
Epoch 43/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 49ms/step - accuracy: 0.6139 - loss: 1.7417 - val_accuracy: 0.0870 - val_loss: 8.6846
Epoch 44/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 49ms/step - accuracy: 0.6176 - loss: 1.7170 - val_accuracy: 0.0879 - val_loss: 8.7438
Epoch 45/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 49ms/step - accuracy: 0.6215 - loss: 1.6935 - val_accuracy: 0.0854 - val_loss: 8.7926
Epoch 46/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 49ms/step - accuracy: 0.6278 - loss: 1.6646 - val_accuracy: 0.0882 - val_loss: 8.8561
Epoch 47/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 50ms/step - accuracy: 0.6341 - loss: 1.6421 - val_accuracy: 0.0847 - val_loss: 8.9050
Epoch 48/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 49ms/step - accuracy: 0.6353 - loss: 1.6216 - val_accuracy: 0.0860 - val_loss: 8.9697
Epoch 49/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 49ms/step - accuracy: 0.6406 - loss: 1.5995 - val_accuracy: 0.0874 - val_loss: 9.0122
Epoch 50/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 49ms/step - accuracy: 0.6457 - loss: 1.5773 - val_accuracy: 0.0865 - val_loss: 9.0701
Epoch 51/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 49ms/step - accuracy: 0.6500 - loss: 1.5587 - val_accuracy: 0.0861 - val_loss: 9.1278
Epoch 52/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 48ms/step - accuracy: 0.6540 - loss: 1.5355 - val_accuracy: 0.0854 - val_loss: 9.1868
Epoch 53/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 49ms/step - accuracy: 0.6590 - loss: 1.5158 - val_accuracy: 0.0834 - val_loss: 9.2302
Epoch 54/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 49ms/step - accuracy: 0.6621 - loss: 1.4985 - val_accuracy: 0.0835 - val_loss: 9.2849
Epoch 55/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 49ms/step - accuracy: 0.6653 - loss: 1.4820 - val_accuracy: 0.0847 - val_loss: 9.3522
Epoch 56/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 49ms/step - accuracy: 0.6684 - loss: 1.4669 - val_accuracy: 0.0821 - val_loss: 9.3859
Epoch 57/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 49ms/step - accuracy: 0.6715 - loss: 1.4486 - val_accuracy: 0.0815 - val_loss: 9.4310
Epoch 58/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 49ms/step - accuracy: 0.6748 - loss: 1.4347 - val_accuracy: 0.0829 - val_loss: 9.4860
Epoch 59/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 49ms/step - accuracy: 0.6777 - loss: 1.4195 - val_accuracy: 0.0821 - val_loss: 9.5411
Epoch 60/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 49ms/step - accuracy: 0.6825 - loss: 1.4008 - val_accuracy: 0.0841 - val_loss: 9.5873
Epoch 61/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 49ms/step - accuracy: 0.6866 - loss: 1.3818 - val_accuracy: 0.0809 - val_loss: 9.6316
Epoch 62/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 49ms/step - accuracy: 0.6880 - loss: 1.3703 - val_accuracy: 0.0817 - val_loss: 9.6807
Epoch 63/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 48ms/step - accuracy: 0.6923 - loss: 1.3550 - val_accuracy: 0.0818 - val_loss: 9.7320
Epoch 64/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 48ms/step - accuracy: 0.6935 - loss: 1.3420 - val_accuracy: 0.0815 - val_loss: 9.7721
Epoch 65/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 49ms/step - accuracy: 0.6972 - loss: 1.3300 - val_accuracy: 0.0817 - val_loss: 9.8437
Epoch 66/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 48ms/step - accuracy: 0.6990 - loss: 1.3171 - val_accuracy: 0.0817 - val_loss: 9.8795
Epoch 67/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 48ms/step - accuracy: 0.7038 - loss: 1.3030 - val_accuracy: 0.0797 - val_loss: 9.9224
Epoch 68/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 49ms/step - accuracy: 0.7042 - loss: 1.2917 - val_accuracy: 0.0813 - val_loss: 9.9792
Epoch 69/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 48ms/step - accuracy: 0.7047 - loss: 1.2869 - val_accuracy: 0.0800 - val_loss: 10.0280
Epoch 70/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 49ms/step - accuracy: 0.7080 - loss: 1.2715 - val_accuracy: 0.0775 - val_loss: 10.0943
Epoch 71/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 49ms/step - accuracy: 0.7118 - loss: 1.2579 - val_accuracy: 0.0780 - val_loss: 10.1138
Epoch 72/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 49ms/step - accuracy: 0.7034 - loss: 1.2783 - val_accuracy: 0.0773 - val_loss: 10.1711
Epoch 73/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 48ms/step - accuracy: 0.7177 - loss: 1.2317 - val_accuracy: 0.0781 - val_loss: 10.2192
Epoch 74/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 49ms/step - accuracy: 0.7196 - loss: 1.2213 - val_accuracy: 0.0789 - val_loss: 10.2468
Epoch 75/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 48ms/step - accuracy: 0.7208 - loss: 1.2160 - val_accuracy: 0.0803 - val_loss: 10.2880
Epoch 76/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 48ms/step - accuracy: 0.7231 - loss: 1.2036 - val_accuracy: 0.0788 - val_loss: 10.3433
Epoch 77/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 50ms/step - accuracy: 0.7257 - loss: 1.1924 - val_accuracy: 0.0786 - val_loss: 10.3827
Epoch 78/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 49ms/step - accuracy: 0.7254 - loss: 1.1876 - val_accuracy: 0.0767 - val_loss: 10.4247
Epoch 79/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 49ms/step - accuracy: 0.7273 - loss: 1.1823 - val_accuracy: 0.0788 - val_loss: 10.4750
Epoch 80/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 49ms/step - accuracy: 0.7266 - loss: 1.1823 - val_accuracy: 0.0768 - val_loss: 10.5177
Epoch 81/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 49ms/step - accuracy: 0.7321 - loss: 1.1603 - val_accuracy: 0.0799 - val_loss: 10.5616
Epoch 82/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 49ms/step - accuracy: 0.7355 - loss: 1.1449 - val_accuracy: 0.0800 - val_loss: 10.6015
Epoch 83/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 49ms/step - accuracy: 0.7341 - loss: 1.1494 - val_accuracy: 0.0753 - val_loss: 10.6289
Epoch 84/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 42s 50ms/step - accuracy: 0.7348 - loss: 1.1449 - val_accuracy: 0.0779 - val_loss: 10.6700
Epoch 85/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 49ms/step - accuracy: 0.7389 - loss: 1.1278 - val_accuracy: 0.0766 - val_loss: 10.7333
Epoch 86/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 49ms/step - accuracy: 0.7398 - loss: 1.1166 - val_accuracy: 0.0797 - val_loss: 10.7589
Epoch 87/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 49ms/step - accuracy: 0.7414 - loss: 1.1143 - val_accuracy: 0.0797 - val_loss: 10.8006
Epoch 88/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 51ms/step - accuracy: 0.7397 - loss: 1.1154 - val_accuracy: 0.0767 - val_loss: 10.8478
Epoch 89/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 49ms/step - accuracy: 0.7448 - loss: 1.0997 - val_accuracy: 0.0781 - val_loss: 10.8647
Epoch 90/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 49ms/step - accuracy: 0.7484 - loss: 1.0861 - val_accuracy: 0.0779 - val_loss: 10.9384
Epoch 91/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 49ms/step - accuracy: 0.7475 - loss: 1.0823 - val_accuracy: 0.0774 - val_loss: 10.9778
Epoch 92/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 48ms/step - accuracy: 0.7472 - loss: 1.0852 - val_accuracy: 0.0760 - val_loss: 10.9852
Epoch 93/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 48ms/step - accuracy: 0.7535 - loss: 1.0640 - val_accuracy: 0.0733 - val_loss: 11.0440
Epoch 94/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 49ms/step - accuracy: 0.7486 - loss: 1.0757 - val_accuracy: 0.0754 - val_loss: 11.0988
Epoch 95/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 48ms/step - accuracy: 0.7519 - loss: 1.0642 - val_accuracy: 0.0796 - val_loss: 11.1269
Epoch 96/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 48ms/step - accuracy: 0.7536 - loss: 1.0545 - val_accuracy: 0.0821 - val_loss: 11.1299
Epoch 97/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.7570 - loss: 1.0437 - val_accuracy: 0.0787 - val_loss: 11.2024
Epoch 98/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 49ms/step - accuracy: 0.7573 - loss: 1.0402 - val_accuracy: 0.0775 - val_loss: 11.2301
Epoch 99/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 29s 49ms/step - accuracy: 0.7573 - loss: 1.0388 - val_accuracy: 0.0776 - val_loss: 11.2650
Epoch 100/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 30s 50ms/step - accuracy: 0.7584 - loss: 1.0318 - val_accuracy: 0.0742 - val_loss: 11.3179

In [45]:
gru_model.save('gru_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [46]:
gru_acc = history_gru.history['accuracy'][-1]
print("gru Accuracy:", gru_acc)

gru Accuracy: 0.7584275007247925