In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("qoute_dataset.csv")

In [3]:
df.head()

                                               quote           Author
0  “The world as we have created it is a process ...  Albert Einstein
1  “It is our choices, Harry, that show what we t...     J.K. Rowling
2  “There are only two ways to live your life. On...  Albert Einstein
3  “The person, be it gentleman or lady, who has ...      Jane Austen
4  “Imperfection is beauty, madness is genius and...   Marilyn Monroe

In [4]:
df.shape

(3038, 2)

In [5]:
quotes = df['quote']
quotes.head()

0    “The world as we have created it is a process ...
1    “It is our choices, Harry, that show what we t...
2    “There are only two ways to live your life. On...
3    “The person, be it gentleman or lady, who has ...
4    “Imperfection is beauty, madness is genius and...
Name: quote, dtype: object

Lower Case

In [6]:
quotes = quotes.str.lower()

In [7]:
quotes.head()

0    “the world as we have created it is a process ...
1    “it is our choices, harry, that show what we t...
2    “there are only two ways to live your life. on...
3    “the person, be it gentleman or lady, who has ...
4    “imperfection is beauty, madness is genius and...
Name: quote, dtype: object

Remove punctuation

In [8]:
import string
translator = str.maketrans('', '', string.punctuation)
quotes = quotes.apply(lambda x: x.translate(translator))

In [9]:
quotes.head()

0    “the world as we have created it is a process ...
1    “it is our choices harry that show what we tru...
2    “there are only two ways to live your life one...
3    “the person be it gentleman or lady who has no...
4    “imperfection is beauty madness is genius and ...
Name: quote, dtype: object

Tokenizetion

In [10]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [11]:
vocab_size = 10000

tokinizer = Tokenizer(num_words=vocab_size)
tokinizer.fit_on_texts(quotes)

In [12]:
word_index = tokinizer.word_index
print(len(word_index))
list(word_index.items())[:15]

8978

[('the', 1),
 ('you', 2),
 ('to', 3),
 ('and', 4),
 ('a', 5),
 ('i', 6),
 ('is', 7),
 ('of', 8),
 ('that', 9),
 ('it', 10),
 ('in', 11),
 ('be', 12),
 ('not', 13),
 ('are', 14),
 ('your', 15)]

In [13]:
sequence = tokinizer.texts_to_sequences(quotes)

In [14]:
for i in range(4):
  print(quotes[i])

“the world as we have created it is a process of our thinking it cannot be changed without changing our thinking”
“it is our choices harry that show what we truly are far more than our abilities”
“there are only two ways to live your life one is as though nothing is a miracle the other is as though everything is a miracle”
“the person be it gentleman or lady who has not pleasure in a good novel must be intolerably stupid”

In [15]:
for i in range(4):
  print(sequence[i])

[713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145, 12, 809, 104, 752, 70, 2461]
[947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294, 52, 54, 70, 3676]
[1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7, 5, 1157, 1, 101, 7, 29, 329, 126, 7, 5, 3677]
[713, 116, 12, 10, 2462, 32, 1043, 30, 82, 13, 601, 11, 5, 74, 1338, 119, 12, 2463, 3678]

In [16]:
print(tokinizer.word_index['“it'])

947

In [17]:
print(tokinizer.word_index['it'])

10

In [18]:
X = []
y = []

for seq in sequence:
  for i in range(1,len(seq)):
    input_seq = seq[:i]
    output_seq = seq[i]
    X.append(input_seq)
    y.append(output_seq)

In [19]:
len(X)

85271

In [20]:
len(y)

85271

Padding

In [21]:
max_len = max(len(x) for x in X)
print(max_len)

745

In [22]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
X_padded = pad_sequences(X, maxlen=max_len, padding='pre')

In [23]:
y = np.array(y)

In [24]:
X_padded.shape

(85271, 745)

In [25]:
y.shape

(85271,)

In [26]:
X_padded

array([[   0,    0,    0, ...,    0,    0,  713],
       [   0,    0,    0, ...,    0,  713,   62],
       [   0,    0,    0, ...,  713,   62,   29],
       ...,
       [   0,    0,    0, ...,    9,   19, 1125],
       [   0,    0,    0, ...,   19, 1125,    3],
       [   0,    0,    0, ..., 1125,    3,  169]], dtype=int32)

In [27]:
y

array([ 62,  29,  19, ...,   3, 169, 101])

One Hot Encodding

In [28]:
from tensorflow.keras.utils import to_categorical
y_one_hot = to_categorical(y, num_classes=vocab_size)

In [29]:
y_one_hot.shape

(85271, 10000)

In [30]:
y_one_hot

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [31]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,SimpleRNN, LSTM, Dense

Embedding

In [32]:
embedding_dim = 50
rnn_units = 128

RNN Model

In [33]:
rnn_model = Sequential()

rnn_model.add(
    Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_len)
)
rnn_model.add(SimpleRNN(units=rnn_units))
rnn_model.add(Dense(units=vocab_size, activation='softmax'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [34]:
rnn_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [ ]:
rnn_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

LSTM Model

In [35]:
lstm_model = Sequential()
lstm_model.add(
    Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_len)
)
lstm_model.add(LSTM(units=rnn_units))
lstm_model.add(Dense(units=vocab_size, activation='softmax'))

In [36]:
lstm_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [37]:
lstm_model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [38]:
epochs =100
batch_size = 128
history_lstm = lstm_model.fit(
    X_padded,
    y_one_hot,
    epochs=100,
    batch_size=128,
    validation_split=0.1
)

Epoch 1/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 37s 51ms/step - accuracy: 0.0390 - loss: 6.7562 - val_accuracy: 0.0398 - val_loss: 6.6888
Epoch 2/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 51ms/step - accuracy: 0.0591 - loss: 6.3148 - val_accuracy: 0.0675 - val_loss: 6.5564
Epoch 3/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.0809 - loss: 6.0543 - val_accuracy: 0.0877 - val_loss: 6.4643
Epoch 4/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.0970 - loss: 5.8437 - val_accuracy: 0.0923 - val_loss: 6.4335
Epoch 5/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.1096 - loss: 5.6690 - val_accuracy: 0.0994 - val_loss: 6.4250
Epoch 6/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.1190 - loss: 5.5040 - val_accuracy: 0.1054 - val_loss: 6.4243
Epoch 7/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1281 - loss: 5.3491 - val_accuracy: 0.1062 - val_loss: 6.4441
Epoch 8/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.1367 - loss: 5.2007 - val_accuracy: 0.1082 - val_loss: 6.4858
Epoch 9/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 54ms/step - accuracy: 0.1430 - loss: 5.0591 - val_accuracy: 0.1102 - val_loss: 6.5185
Epoch 10/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1508 - loss: 4.9223 - val_accuracy: 0.1125 - val_loss: 6.5710
Epoch 11/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.1577 - loss: 4.7896 - val_accuracy: 0.1129 - val_loss: 6.6255
Epoch 12/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.1654 - loss: 4.6619 - val_accuracy: 0.1116 - val_loss: 6.6818
Epoch 13/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 54ms/step - accuracy: 0.1722 - loss: 4.5383 - val_accuracy: 0.1120 - val_loss: 6.7296
Epoch 14/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1820 - loss: 4.4168 - val_accuracy: 0.1126 - val_loss: 6.8040
Epoch 15/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1920 - loss: 4.2985 - val_accuracy: 0.1162 - val_loss: 6.8739
Epoch 16/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.2041 - loss: 4.1851 - val_accuracy: 0.1157 - val_loss: 6.9387
Epoch 17/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.2177 - loss: 4.0729 - val_accuracy: 0.1126 - val_loss: 7.0159
Epoch 18/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.2308 - loss: 3.9668 - val_accuracy: 0.1162 - val_loss: 7.0952
Epoch 19/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.2461 - loss: 3.8646 - val_accuracy: 0.1141 - val_loss: 7.1750
Epoch 20/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.2595 - loss: 3.7699 - val_accuracy: 0.1139 - val_loss: 7.2572
Epoch 21/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.2740 - loss: 3.6804 - val_accuracy: 0.1132 - val_loss: 7.3326
Epoch 22/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.2856 - loss: 3.5960 - val_accuracy: 0.1126 - val_loss: 7.4095
Epoch 23/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.2980 - loss: 3.5175 - val_accuracy: 0.1125 - val_loss: 7.4976
Epoch 24/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3094 - loss: 3.4422 - val_accuracy: 0.1078 - val_loss: 7.5898
Epoch 25/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.3214 - loss: 3.3718 - val_accuracy: 0.1083 - val_loss: 7.6591
Epoch 26/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3320 - loss: 3.3029 - val_accuracy: 0.1092 - val_loss: 7.7280
Epoch 27/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.3420 - loss: 3.2401 - val_accuracy: 0.1046 - val_loss: 7.7885
Epoch 28/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.3517 - loss: 3.1782 - val_accuracy: 0.1049 - val_loss: 7.8661
Epoch 29/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3621 - loss: 3.1177 - val_accuracy: 0.1054 - val_loss: 7.9580
Epoch 30/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3712 - loss: 3.0620 - val_accuracy: 0.1053 - val_loss: 8.0107
Epoch 31/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3808 - loss: 3.0056 - val_accuracy: 0.1054 - val_loss: 8.0726
Epoch 32/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.3896 - loss: 2.9512 - val_accuracy: 0.1040 - val_loss: 8.1503
Epoch 33/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.4001 - loss: 2.9008 - val_accuracy: 0.1027 - val_loss: 8.2171
Epoch 34/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 55ms/step - accuracy: 0.4076 - loss: 2.8504 - val_accuracy: 0.1014 - val_loss: 8.2690
Epoch 35/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4157 - loss: 2.8004 - val_accuracy: 0.1028 - val_loss: 8.3548
Epoch 36/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 54ms/step - accuracy: 0.4243 - loss: 2.7538 - val_accuracy: 0.1005 - val_loss: 8.4173
Epoch 37/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.4327 - loss: 2.7092 - val_accuracy: 0.1030 - val_loss: 8.4765
Epoch 38/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4410 - loss: 2.6634 - val_accuracy: 0.1037 - val_loss: 8.5293
Epoch 39/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.4478 - loss: 2.6214 - val_accuracy: 0.0997 - val_loss: 8.6023
Epoch 40/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.4551 - loss: 2.5782 - val_accuracy: 0.0980 - val_loss: 8.6606
Epoch 41/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4628 - loss: 2.5384 - val_accuracy: 0.0979 - val_loss: 8.7180
Epoch 42/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 54ms/step - accuracy: 0.4702 - loss: 2.4983 - val_accuracy: 0.0962 - val_loss: 8.7816
Epoch 43/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 53ms/step - accuracy: 0.4779 - loss: 2.4577 - val_accuracy: 0.0958 - val_loss: 8.8646
Epoch 44/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4842 - loss: 2.4212 - val_accuracy: 0.0938 - val_loss: 8.9049
Epoch 45/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4913 - loss: 2.3836 - val_accuracy: 0.0953 - val_loss: 8.9921
Epoch 46/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 42s 54ms/step - accuracy: 0.4986 - loss: 2.3492 - val_accuracy: 0.0956 - val_loss: 9.0212
Epoch 47/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5042 - loss: 2.3145 - val_accuracy: 0.0915 - val_loss: 9.0918
Epoch 48/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5116 - loss: 2.2802 - val_accuracy: 0.0943 - val_loss: 9.1625
Epoch 49/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5172 - loss: 2.2471 - val_accuracy: 0.0929 - val_loss: 9.2062
Epoch 50/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5239 - loss: 2.2140 - val_accuracy: 0.0916 - val_loss: 9.2787
Epoch 51/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5295 - loss: 2.1835 - val_accuracy: 0.0938 - val_loss: 9.3168
Epoch 52/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 54ms/step - accuracy: 0.5346 - loss: 2.1519 - val_accuracy: 0.0917 - val_loss: 9.3718
Epoch 53/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5408 - loss: 2.1229 - val_accuracy: 0.0888 - val_loss: 9.4363
Epoch 54/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5471 - loss: 2.0936 - val_accuracy: 0.0923 - val_loss: 9.4850
Epoch 55/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5529 - loss: 2.0652 - val_accuracy: 0.0899 - val_loss: 9.5491
Epoch 56/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5576 - loss: 2.0361 - val_accuracy: 0.0915 - val_loss: 9.5864
Epoch 57/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.5633 - loss: 2.0087 - val_accuracy: 0.0904 - val_loss: 9.6520
Epoch 58/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.5700 - loss: 1.9822 - val_accuracy: 0.0886 - val_loss: 9.7089
Epoch 59/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5748 - loss: 1.9562 - val_accuracy: 0.0896 - val_loss: 9.7621
Epoch 60/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 55ms/step - accuracy: 0.5792 - loss: 1.9311 - val_accuracy: 0.0905 - val_loss: 9.7905
Epoch 61/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5854 - loss: 1.9058 - val_accuracy: 0.0871 - val_loss: 9.8855
Epoch 62/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5900 - loss: 1.8807 - val_accuracy: 0.0870 - val_loss: 9.9278
Epoch 63/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5959 - loss: 1.8566 - val_accuracy: 0.0847 - val_loss: 9.9818
Epoch 64/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.5997 - loss: 1.8344 - val_accuracy: 0.0875 - val_loss: 10.0266
Epoch 65/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6047 - loss: 1.8109 - val_accuracy: 0.0856 - val_loss: 10.0857
Epoch 66/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6093 - loss: 1.7878 - val_accuracy: 0.0862 - val_loss: 10.1301
Epoch 67/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6136 - loss: 1.7665 - val_accuracy: 0.0842 - val_loss: 10.1731
Epoch 68/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6187 - loss: 1.7443 - val_accuracy: 0.0850 - val_loss: 10.2256
Epoch 69/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.6228 - loss: 1.7236 - val_accuracy: 0.0847 - val_loss: 10.3017
Epoch 70/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6269 - loss: 1.7015 - val_accuracy: 0.0851 - val_loss: 10.3517
Epoch 71/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.6319 - loss: 1.6818 - val_accuracy: 0.0831 - val_loss: 10.3931
Epoch 72/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.6358 - loss: 1.6628 - val_accuracy: 0.0848 - val_loss: 10.4474
Epoch 73/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6398 - loss: 1.6423 - val_accuracy: 0.0827 - val_loss: 10.5020
Epoch 74/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 56ms/step - accuracy: 0.6447 - loss: 1.6238 - val_accuracy: 0.0823 - val_loss: 10.5499
Epoch 75/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6470 - loss: 1.6050 - val_accuracy: 0.0827 - val_loss: 10.6080
Epoch 76/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 55ms/step - accuracy: 0.6509 - loss: 1.5874 - val_accuracy: 0.0849 - val_loss: 10.6502
Epoch 77/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6548 - loss: 1.5707 - val_accuracy: 0.0826 - val_loss: 10.7037
Epoch 78/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6591 - loss: 1.5505 - val_accuracy: 0.0818 - val_loss: 10.7552
Epoch 79/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6635 - loss: 1.5336 - val_accuracy: 0.0808 - val_loss: 10.8056
Epoch 80/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.6668 - loss: 1.5170 - val_accuracy: 0.0826 - val_loss: 10.8608
Epoch 81/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6698 - loss: 1.4991 - val_accuracy: 0.0799 - val_loss: 10.8939
Epoch 82/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.6740 - loss: 1.4827 - val_accuracy: 0.0807 - val_loss: 10.9742
Epoch 83/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6767 - loss: 1.4688 - val_accuracy: 0.0808 - val_loss: 10.9744
Epoch 84/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.6806 - loss: 1.4497 - val_accuracy: 0.0803 - val_loss: 11.0656
Epoch 85/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.6838 - loss: 1.4356 - val_accuracy: 0.0808 - val_loss: 11.0843
Epoch 86/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.6882 - loss: 1.4192 - val_accuracy: 0.0799 - val_loss: 11.1306
Epoch 87/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 56ms/step - accuracy: 0.6910 - loss: 1.4061 - val_accuracy: 0.0789 - val_loss: 11.2028
Epoch 88/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.6915 - loss: 1.3916 - val_accuracy: 0.0799 - val_loss: 11.2441
Epoch 89/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.6970 - loss: 1.3745 - val_accuracy: 0.0795 - val_loss: 11.3001
Epoch 90/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 56ms/step - accuracy: 0.7003 - loss: 1.3621 - val_accuracy: 0.0780 - val_loss: 11.3115
Epoch 91/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.7029 - loss: 1.3473 - val_accuracy: 0.0797 - val_loss: 11.3745
Epoch 92/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.7055 - loss: 1.3343 - val_accuracy: 0.0773 - val_loss: 11.4368
Epoch 93/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 42s 56ms/step - accuracy: 0.7074 - loss: 1.3205 - val_accuracy: 0.0784 - val_loss: 11.4950
Epoch 94/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 55ms/step - accuracy: 0.7113 - loss: 1.3079 - val_accuracy: 0.0776 - val_loss: 11.5381
Epoch 95/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.7148 - loss: 1.2926 - val_accuracy: 0.0789 - val_loss: 11.5916
Epoch 96/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.7171 - loss: 1.2807 - val_accuracy: 0.0769 - val_loss: 11.6281
Epoch 97/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.7201 - loss: 1.2690 - val_accuracy: 0.0762 - val_loss: 11.6571
Epoch 98/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.7215 - loss: 1.2569 - val_accuracy: 0.0768 - val_loss: 11.7092
Epoch 99/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.7245 - loss: 1.2439 - val_accuracy: 0.0770 - val_loss: 11.7426
Epoch 100/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.7284 - loss: 1.2316 - val_accuracy: 0.0774 - val_loss: 11.8148

In [41]:
import os
os.listdir()

['.config', 'qoute_dataset.csv', 'sample_data']

In [45]:
lstm_model.save("lstm_model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [46]:
from tensorflow.keras.models import load_model
lstm_model = load_model("lstm_model.h5")

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [47]:
index_to_word = {}
for word, index in word_index.items():
  index_to_word[index] = word

In [48]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [49]:
def predictor(model,tokenizer,text,max_len):
  text = text.lower()

  seq = tokenizer.texts_to_sequences([text])[0]
  seq = pad_sequences([seq], maxlen=max_len, padding='pre')

  pred = model.predict(seq,verbose = 0)
  pred_index = np.argmax(pred)
  return index_to_word[pred_index]

In [50]:
seed_text = "what are you"
next_word = predictor(lstm_model,tokinizer,seed_text,max_len)
print(next_word)

implying

In [55]:
seed_text = "My name is Dipu and "
next_word = predictor(lstm_model,tokinizer,seed_text,max_len)
print(next_word)

whether

In [62]:
def generate_text(model,tokenizer,seed_text,max_len,n_words):
  for _ in range(n_words):
    next_word = predictor(model,tokenizer,seed_text,max_len)
    if next_word == "":
      break
    seed_text += " " + next_word
  return seed_text

In [61]:
seed = "are you a "
generate_text = generate_text(lstm_model,tokinizer,seed,max_len,10)
print(generate_text)

are you a  thousand lives before you read a book and people who

In [63]:
seed = "my name is "
generate_text = generate_text(lstm_model,tokinizer,seed,max_len,10)
print(generate_text)

my name is  celaena sardothien but it makes no difference but i deserve

In [64]:
import pickle
with open("tokenizer.pkl", "wb") as f:
  pickle.dump(tokinizer, f)

In [65]:
with open("max_len.pkl", "wb") as f:
  pickle.dump(max_len, f)